### ISSUE TITLE
setup requirements hardcode aiida-core version

### ISSUE THREAD

**Issue by yakutovicha** [aiidaplugins/aiida-crystal17#30]
The current setup requirements pin the aiida-core version:

https://github.com/chrisjsewell/aiida-crystal17/blob/1eab9635e81a29956b0113bc91e13d5a4ee4269d/setup.json#L69

Please replace this with something like `"aiida-core>=1.0.0b6,<2.0.0"`

**Comment by chrisjsewell** [comment]
Yep will do, as soon as I fix the `WorkChain`s that @sphuber broke 😜 (see #28)
